export const CHANGE_INPUT_VALUE =  'change_input_value'
export const SUBMIT_VALUE = 'submit_value'
export const DELETE_ITEM = 'delete_item'
export const INIT_LIST = 'init_list'
export const GET_INIT_LIST = 'get_init_list'